version: '3.1'
services:
  cnab-persister-api:
    image: 'cnab-persister.jar'
    container_name: cnab-persister-application
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-cnab-persister
    command:
      - dockerize -wait tcp://db-cnab-persister:5432
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-cnab-persister:5432/cnab_persister
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db-cnab-persister:
    image: postgres:10.5
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db-initial-script.sql:/docker-entrypoint-initdb.d/db-initial-script.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cnab_persister
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
